"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Ban, KeyRound, LogIn, Plus, Save, ShieldCheck, Trash2, UserRoundCheck } from "lucide-react";
import { api } from "@/lib/api";
import { startSellerImpersonation } from "@/lib/auth";
import { useLanguage } from "@/lib/site-language";

type Seller = { _id: string; name: string; showroomName: string; email: string; phone?: string; address?: string; adminNotes?: string; accountStatus: string; totalCars: number; pendingCars: number; createdAt: string; lastLoginAt?: string };
const empty = { name: "", showroomName: "", email: "", phone: "", address: "", password: "" };

export default function AdminSellersPage() {
  const router = useRouter();
  const { language } = useLanguage();
  const ar = language === "ar";
  const [items, setItems] = useState<Seller[]>([]);
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState<string | null>(null);
  const [draft, setDraft] = useState<Partial<Seller>>({});
  const [error, setError] = useState("");
  const load = () => api.get("/admin/sellers").then(({ data }) => setItems(data?.items || [])).catch((requestError) => setError(requestError?.response?.data?.message || (ar ? "تعذر تحميل حسابات البائعين" : "Unable to load seller accounts")));
  useEffect(() => { load(); }, []);
  const patchStatus = async (seller: Seller, accountStatus: string) => { await api.patch(`/admin/sellers/${seller._id}/status`, { accountStatus }); setItems((current) => current.map((item) => item._id === seller._id ? { ...item, accountStatus } : item)); };

  const labels: Record<string, string> = ar ? { name: "اسم المسؤول", showroomName: "اسم المعرض / البائع", email: "البريد الإلكتروني", phone: "الهاتف / واتساب", address: "العنوان", password: "كلمة المرور", adminNotes: "ملاحظات الإدارة" } : { name: "Contact name", showroomName: "Showroom / seller name", email: "Email", phone: "Phone / WhatsApp", address: "Address", password: "Password", adminNotes: "Admin notes" };
  const statusLabel = (status: string) => ar ? ({ Pending: "قيد المراجعة", Active: "نشط", Suspended: "موقوف", Banned: "محظور" } as Record<string, string>)[status] || status : status;
  return <section className="space-y-5"><div className="rounded-[28px] bg-zinc-950 p-7 text-white"><p className="text-sm font-black uppercase tracking-[.25em] text-emerald-400">{ar ? "إدارة الشركاء" : "Partner management"}</p><h1 className="mt-3 text-4xl font-black">{ar ? "حسابات البائعين" : "Seller accounts"}</h1><p className="mt-3 text-white/65">{ar ? "أنشئ الحسابات، وافق على الطلبات، أوقف الدخول، غيّر كلمات المرور أو ادخل إلى لوحة البائع." : "Create accounts, approve requests, suspend access, reset passwords, or enter an active seller dashboard."}</p></div>
    <form className="grid gap-3 rounded-[26px] border border-zinc-200 bg-white p-5 dark:border-white/10 dark:bg-zinc-900 md:grid-cols-2 xl:grid-cols-3" onSubmit={async (event) => { event.preventDefault(); setError(""); try { await api.post("/admin/sellers", form); setForm(empty); load(); } catch (requestError: any) { setError(requestError?.response?.data?.message || (ar ? "تعذر إنشاء البائع" : "Unable to create seller")); } }}><h2 className="col-span-full text-xl font-black">{ar ? "إنشاء حساب بائع نشط" : "Create an active seller account"}</h2>{Object.entries(form).map(([key, value]) => <label key={key} className="grid gap-1.5 text-xs font-bold capitalize text-zinc-500">{labels[key] || key}<input type={key === "password" ? "password" : key === "email" ? "email" : "text"} required={key !== "address"} minLength={key === "password" ? 8 : undefined} value={value} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} className="rounded-xl border bg-transparent px-3 py-2.5 text-sm text-zinc-950 outline-none focus:border-brand dark:text-white" /></label>)}<button className="inline-flex items-center justify-center gap-2 rounded-xl bg-brand px-4 py-3 font-black text-white md:self-end"><Plus className="h-4 w-4" />{ar ? "إنشاء الحساب" : "Create account"}</button>{error ? <p className="col-span-full text-sm text-red-600">{error}</p> : null}</form>
    <div className="grid gap-4">{items.map((seller) => <article key={seller._id} className="rounded-[24px] border border-zinc-200 bg-white p-5 dark:border-white/10 dark:bg-zinc-900"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black">{seller.showroomName || seller.name}</h2><span className={`rounded-full px-3 py-1 text-xs font-black ${seller.accountStatus === "Active" ? "bg-emerald-100 text-emerald-800" : seller.accountStatus === "Pending" ? "bg-amber-100 text-amber-800" : "bg-red-100 text-red-700"}`}>{statusLabel(seller.accountStatus)}</span></div><p className="mt-1 text-sm text-zinc-500">{seller.name} · {seller.email} · {seller.phone || (ar ? "لا يوجد هاتف" : "No phone")}</p><p className="mt-2 text-xs text-zinc-500">{seller.totalCars} {ar ? "مركبة" : "vehicles"} · {seller.pendingCars} {ar ? "قيد الموافقة" : "pending approval"}</p></div><div className="flex flex-wrap gap-2"><select value={seller.accountStatus} onChange={(event) => patchStatus(seller, event.target.value)} className="rounded-xl border bg-transparent px-3 py-2 text-sm font-bold"><option value="Pending">{statusLabel("Pending")}</option><option value="Active">{statusLabel("Active")}</option><option value="Suspended">{statusLabel("Suspended")}</option><option value="Banned">{statusLabel("Banned")}</option></select><button type="button" onClick={() => { setEditing(seller._id); setDraft(seller); }} className="rounded-xl border px-3 py-2 text-sm font-bold">{ar ? "تعديل" : "Edit"}</button><button type="button" disabled={seller.accountStatus !== "Active"} onClick={async () => { const { data } = await api.post(`/admin/sellers/${seller._id}/impersonate`); startSellerImpersonation(data.accessToken, data.user); router.replace("/seller"); router.refresh(); }} className="inline-flex items-center gap-1 rounded-xl bg-zinc-950 px-3 py-2 text-sm font-bold text-white disabled:opacity-40"><LogIn className="h-4 w-4" />{ar ? "دخول" : "Enter"}</button><button type="button" onClick={async () => { const password = prompt(ar ? "كلمة المرور الجديدة (8 أحرف على الأقل)" : "New seller password (8 characters minimum)"); if (!password) return; await api.put(`/admin/sellers/${seller._id}/password`, { password }); alert(ar ? "تم تحديث كلمة المرور" : "Password updated"); }} className="rounded-xl border border-amber-200 p-2 text-amber-700" title={ar ? "تغيير كلمة المرور" : "Reset password"}><KeyRound className="h-4 w-4" /></button><button type="button" onClick={async () => { if (!confirm(ar ? "حذف حساب البائع وإخفاء مركباته؟" : "Delete this seller account and hide its vehicles?")) return; await api.delete(`/admin/sellers/${seller._id}`); setItems((current) => current.filter((item) => item._id !== seller._id)); }} className="rounded-xl border border-red-200 p-2 text-red-600" title={ar ? "حذف الحساب" : "Delete account"}><Trash2 className="h-4 w-4" /></button></div></div>
      {editing === seller._id ? <div className="mt-5 grid gap-3 border-t border-zinc-200 pt-5 sm:grid-cols-2 lg:grid-cols-3">{["name", "showroomName", "email", "phone", "address", "adminNotes"].map((key) => <label key={key} className="grid gap-1 text-xs font-bold capitalize text-zinc-500">{labels[key] || key}<input value={String((draft as any)[key] || "")} onChange={(event) => setDraft((current) => ({ ...current, [key]: event.target.value }))} className="rounded-xl border bg-transparent px-3 py-2 text-sm text-zinc-950 dark:text-white" /></label>)}<div className="flex items-end gap-2"><button type="button" onClick={async () => { const { data } = await api.put(`/admin/sellers/${seller._id}`, draft); setItems((current) => current.map((item) => item._id === seller._id ? { ...item, ...draft, ...data.item } : item)); setEditing(null); }} className="inline-flex items-center gap-2 rounded-xl bg-brand px-4 py-2.5 text-sm font-black text-white"><Save className="h-4 w-4" />{ar ? "حفظ" : "Save"}</button><button type="button" onClick={() => setEditing(null)} className="rounded-xl border px-4 py-2.5 text-sm font-bold">{ar ? "إلغاء" : "Cancel"}</button></div></div> : null}
    </article>)}</div>
  </section>;
}
